services:
  # Backend
  - type: web
    name: yolo-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    region: singapore
    plan: free

    envVars:
      - key: PORT
        value: 8000

    healthCheckPath: /health

  # Frontend
  - type: web
    name: yolo-frontend
    runtime: docker
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    region: singapore
    plan: free

    envVars:
      - key: VITE_API_BASE_URL
        sync : false